# Site settings
title: Neural Circuits and Computations Unit
short-title: Kang Group
affiliation: RIKEN Center for Brain Science
email: louis.kang@riken.jp
url: https://louiskang.group
description: "We are a computational neuroscience research group that studies how memories are stored by neural circuits in our brains."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#64a19d'

# Build settings
markdown: kramdown
permalink: pretty
