# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Site settings
url: https://louiskang.group
title: Kang Group &bull; RIKEN Center for Brain Science

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-0: '#64a19d'
  primary-1: '#548b87'
  primary-2: '#4f837f'
  primary-3: '#467370'

icons:
  copy: <i class="material-icons">content_copy</i> 
  pdf: <i class="material-icons">save_alt</i> 
  link: <i class="material-icons">link</i> 
  more: <i class="material-icons">add</i> 
  less: <i class="material-icons">remove</i> 
  forward: <i class="material-icons">arrow_forward</i> 
  back: <i class="material-icons">arrow_back</i> 

